/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import static java.util.Collections.list;
import static java.util.Collections.reverse;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Punto2D;
import modelo.Utilidades;
/**
 *
 * @author santiago.londono_men
 */
public class UIpunto extends javax.swing.JFrame  {

    LinkedList<Punto2D> listaPuntos = new LinkedList<>();
    
  

    /**
     * Creates new form UIpunto
     */
   public UIpunto() {
    initComponents();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        variablex = new javax.swing.JTextField();
        variabley = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreacoordenada = new javax.swing.JTextArea();
        panelcoordenada = new javax.swing.JPanel();
        Guardar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        Guardar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jTextArea1.setColumns(3);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("X = ");
        jLabel2.setToolTipText("");

        variablex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variablexActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Y =");
        jLabel3.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coordenadas Registradas");

        TextAreacoordenada.setColumns(3);
        TextAreacoordenada.setRows(5);
        jScrollPane2.setViewportView(TextAreacoordenada);

        panelcoordenada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelcoordenada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelcoordenadaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelcoordenadaLayout = new javax.swing.GroupLayout(panelcoordenada);
        panelcoordenada.setLayout(panelcoordenadaLayout);
        panelcoordenadaLayout.setHorizontalGroup(
            panelcoordenadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        panelcoordenadaLayout.setVerticalGroup(
            panelcoordenadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        Guardar.setText("Guardar Coordenadas");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar Coordenadas");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        Guardar1.setText("Guardar Coordenadas 2");
        Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Ordenar");

        jMenuItem1.setText("Mayor a menor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Menor a mayor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem8.setText("Ordenar X");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem7.setText("Ordenar Y ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem3.setText("Invertir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Sublista-X");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Sublista-Y");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Concatenar X.Y");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelcoordenada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Guardar1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(variablex, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(variabley, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Salir)))
                        .addGap(27, 27, 27)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(panelcoordenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(Guardar1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Guardar)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variablex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variabley, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrar))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
        // El código generado por el editor visual de NetBeans aquí...
        // ...
    private void variablexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variablexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_variablexActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        
        boolean t=Utilidades.escribirCoordenadas(listaPuntos, "CoordenadasPuntos.txt");
        if(t){
            JOptionPane.showMessageDialog(rootPane, "Si se guardo el archivo");
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se guardo el archivo");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void panelcoordenadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcoordenadaMouseClicked
        // TODO add your handling code here:
        double coorX=evt.getX();
        double coorY=evt.getY();
        Punto2D objP=new Punto2D(coorX, coorY);
        listaPuntos.add(objP);
  
    }//GEN-LAST:event_panelcoordenadaMouseClicked

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        
        TextAreacoordenada.setText(mostrarC(listaPuntos));
     
        
        
    }//GEN-LAST:event_mostrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

    LinkedList<Punto2D> listaOrdenada = new LinkedList<>(listaPuntos);


    Collections.sort(listaOrdenada, new Comparator<Punto2D>() {
   
        public int compare(Punto2D punto1, Punto2D punto2) {

            int comparacionX = Double.compare(punto2.getX(), punto1.getX());


            if (comparacionX == 0) {
                return Double.compare(punto1.getY(), punto2.getY());
            } else {
                return comparacionX;
            }
        }
    });


    TextAreacoordenada.setText(mostrarC(listaOrdenada));
 
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    reverse(listaPuntos);
    TextAreacoordenada.setText(mostrarC(listaPuntos));
    
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
   

    LinkedList<Punto2D> coordenadasX = new LinkedList<>();


    for (Punto2D punto : listaPuntos) {
        coordenadasX.add(new Punto2D(punto.getX(), 0)); 
    }


    boolean exito = Utilidades.escribirCoordenadas(coordenadasX, "coordenadasX.txt");
    

    if (exito) {
        JOptionPane.showMessageDialog(this, "Se ha creado el archivo coordenadasX.txt con las coordenadas X.");
    } else {
        JOptionPane.showMessageDialog(this, "Error al crear el archivo coordenadasX.txt");
    }
    TextAreacoordenada.setText(mostrarC(coordenadasX));
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar1ActionPerformed

          boolean t=Utilidades.escribirCoordenadas(listaPuntos, "CoordenadasPuntos2.txt");
        if(t){
            JOptionPane.showMessageDialog(rootPane, "Si se guardo el archivo");
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se guardo el archivo");
        }
           
        
    }//GEN-LAST:event_Guardar1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        

    LinkedList<Punto2D> coordenadasY = new LinkedList<>();


    for (Punto2D punto : listaPuntos) {
        coordenadasY.add(new Punto2D(0, punto.getY()));
    }


    boolean exito = Utilidades.escribirCoordenadas(coordenadasY, "coordenadasY.txt");
    

    if (exito) {
        JOptionPane.showMessageDialog(this, "Se ha creado el archivo coordenadasY.txt con las coordenadas Y.");
    } else {
        JOptionPane.showMessageDialog(this, "Error al crear el archivo coordenadasY.txt");
    }

        TextAreacoordenada.setText(mostrarC(coordenadasY));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:

    LinkedList<Punto2D> listaOrdenada = new LinkedList<>(listaPuntos);

    
    Collections.sort(listaOrdenada, new Comparator<Punto2D>() {
    
        public int compare(Punto2D punto1, Punto2D punto2) {

            int comparacionX = Double.compare(punto1.getX(), punto2.getX());

           
            if (comparacionX == 0) {
                return Double.compare(punto1.getY(), punto2.getY());
            } else {
                return comparacionX;
            }
        }
    });

 
    TextAreacoordenada.setText(mostrarC(listaOrdenada));
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
      // Leer las coordenadas X e Y desde los archivos de texto
    LinkedList<Punto2D> coordenadasX = Utilidades.leerCoordenadas("coordenadasX.txt");
    LinkedList<Punto2D> coordenadasY = Utilidades.leerCoordenadas("coordenadasY.txt");

  
    LinkedList<Punto2D> coordenadasConcatenadas = new LinkedList<>(coordenadasX);
    coordenadasConcatenadas.addAll(coordenadasY);

   
    TextAreacoordenada.setText(mostrarC(coordenadasConcatenadas));


    boolean exito = Utilidades.escribirCoordenadas(coordenadasConcatenadas, "coordenadasConcatenadas.txt");
    if (exito) {
        JOptionPane.showMessageDialog(this, "Archivo 'coordenadasConcatenadas.txt' creado exitosamente.");
    } else {
        JOptionPane.showMessageDialog(this, "Error al crear el archivo.");
    }

        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
     if(listaPuntos.size() <= 1)
         return;
     
     for (int i = 1; i < listaPuntos.size(); i++){
         Punto2D key = listaPuntos.get(i);
         int j = i - 1;
         
         
         while (j >= 0  && listaPuntos.get(j).getY()> key.getY()){
             listaPuntos.set(j+1, listaPuntos.get (j));
             j--;
         }
        listaPuntos.set(j + 1, key);
        
        TextAreacoordenada.setText(mostrarC(listaPuntos));
     }
     
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       
             if(listaPuntos.size() <= 1)
         return;
     
     for (int i = 1; i < listaPuntos.size(); i++){
         Punto2D key = listaPuntos.get(i);
         int j = i - 1;
         
         
         while (j >= 0  && listaPuntos.get(j).getX()> key.getX()){
             listaPuntos.set(j+1, listaPuntos.get (j));
             j--;
         }
        listaPuntos.set(j + 1, key);
        
        TextAreacoordenada.setText(mostrarC(listaPuntos));
     }
     
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    public String mostrarC(LinkedList<Punto2D> l){
        String mostrarl="";
        for (int i = 0; i < l.size(); i++) {
            Punto2D get = l.get(i);
            mostrarl+=get.toString()+"\n";
        }
        
        
        return mostrarl;
    }
    

      
    /**
     * @param args the command line arguments
     */
        
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIpunto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JButton Salir;
    private javax.swing.JTextArea TextAreacoordenada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mostrar;
    private javax.swing.JPanel panelcoordenada;
    private javax.swing.JTextField variablex;
    private javax.swing.JTextField variabley;
    // End of variables declaration//GEN-END:variables

   
}

